from __future__ import annotations

import shlex

from .models import ExperimentCreate, SHELL_BASH


def demo_training_command(index: int, should_fail: bool = False) -> str:
    lines = [
        "import random",
        "import sys",
        "import time",
        f"random.seed({index})",
        f"print('[PipeDL demo] preparing dataset shard {index}', flush=True)",
        "time.sleep(2)",
        f"print('[PipeDL demo] building model demo_net_{index}', flush=True)",
        "time.sleep(2)",
        "best = 0.0",
        "for epoch in range(1, 51):",
        "    loss = 1.0 / epoch + random.random() * 0.04",
        "    acc = min(0.995, 0.50 + epoch * 0.009 + random.random() * 0.02)",
        "    best = max(best, acc)",
        f"    print(f'[train-{index}] epoch {{epoch:02d}}/50 simulated_time=60s loss={{loss:.4f}} acc={{acc:.3f}} best={{best:.3f}}', flush=True)",
        "    time.sleep(60)",
        "print('[PipeDL demo] validating checkpoint', flush=True)",
        "time.sleep(5)",
    ]
    if should_fail:
        lines.extend(
            [
                "print('[PipeDL demo] simulated CUDA OOM during final export', file=sys.stderr, flush=True)",
                "sys.exit(2)",
            ]
        )
    else:
        lines.append(f"print('[PipeDL demo] training complete for demo-train-{index:02d}', flush=True)")
    return "python3 -c " + shlex.quote("\n".join(lines))


def demo_experiment(index: int) -> ExperimentCreate:
    return ExperimentCreate(
        name=f"demo-train-{index:02d}",
        command=demo_training_command(index, should_fail=index == 4),
        shell=SHELL_BASH,
        cwd=".",
        created_by="demo",
        tags="demo,training",
        notes="Simulated training command generated by PipeDL.",
    )
